# Generated by Django 5.0.6 on 2024-05-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("task", models.IntegerField(verbose_name="task")),
            ],
            options={
                "verbose_name": "achievement",
                "verbose_name_plural": "achievements",
            },
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField(verbose_name="amount")),
            ],
            options={
                "verbose_name": "information",
                "verbose_name_plural": "information",
            },
        ),
    ]
